# Generated by Django 6.0.4 on 2026-04-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='time',
        ),
        migrations.AddField(
            model_name='seminar',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
