# Generated by Django 6.0.4 on 2026-04-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0003_seminarregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarregistration',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
    ]
