# Generated by Django 6.0.4 on 2026-04-18 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0004_seminarregistration_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='seminars.seminar'),
        ),
    ]
