# Generated by Django 6.0.4 on 2026-04-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0005_seminar_created_at_alter_seminarregistration_seminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarregistration',
            name='attendance_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
