# Generated by Django 6.0.4 on 2026-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0006_seminarregistration_attendance_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
