# Generated by Django 6.0.4 on 2026-04-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_seminar_registration_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='registration_open',
        ),
    ]
