# Generated by Django 6.0.4 on 2026-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0008_remove_seminar_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='certificate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='certificate_logo_left',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_logos/'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='certificate_logo_right',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_logos/'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='certificate_signature',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_signatures/'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='certificate_title',
            field=models.CharField(default='Certificate of Participation', max_length=200),
        ),
    ]
