# Generated by Django 6.0.4 on 2026-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0009_seminar_certificate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarregistration',
            name='verification_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
