# Generated by Django 6.0.4 on 2026-04-21 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0010_seminarregistration_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarregistration',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
