# Generated by Django 6.0.4 on 2026-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0011_alter_seminarregistration_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='attendance_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
