# Generated by Django 6.0.4 on 2026-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0012_seminar_attendance_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='certificate_logo_left',
            new_name='certificate_logo_1',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='certificate_logo_right',
            new_name='certificate_logo_2',
        ),
        migrations.AddField(
            model_name='seminar',
            name='certificate_logo_3',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_logos/'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='certificate_logo_4',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_logos/'),
        ),
    ]
