# Generated by Django 6.0.4 on 2026-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0013_rename_certificate_logo_left_seminar_certificate_logo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='attendance_code',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='attendance_code_created_at',
        ),
        migrations.AddField(
            model_name='seminar',
            name='attendance_link_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='attendee_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='attendee_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='attendee_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
