# Generated by Django 6.0.4 on 2026-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0014_remove_seminar_attendance_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarregistration',
            name='attendee_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='attendee_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='attendee_phone',
            field=models.CharField(max_length=20),
        ),
    ]
