# Generated by Django 6.0.4 on 2026-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0015_alter_seminarregistration_attendee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='attendance_link_token',
            field=models.UUIDField(blank=True, editable=False, unique=True),
        ),
    ]
