# Generated by Django 6.0.4 on 2026-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0016_alter_seminar_attendance_link_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='attendance_link_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
