# Generated by Django 6.0.4 on 2026-05-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0018_alter_seminar_attendance_link_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='attendance_link_token',
        ),
    ]
