# Generated by Django 6.0.4 on 2026-05-08 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0019_remove_seminar_attendance_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='attendance_link_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
